name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run build
        env:
          AUTH_SECRET: dummy-secret-for-ci
          AUTH_GOOGLE_ID: dummy
          AUTH_GOOGLE_SECRET: dummy
          DATABASE_URL: postgresql://dummy:dummy@localhost:5432/dummy
      - run: npm test
